load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "election",
    srcs = [
        "model.cc",
        "results.cc",
        "results_source.cc",
    ],
    hdrs = [
        "model.h",
        "results.h",
        "results_source.h",
    ],
    deps = [
        "//src/geo",
        "@nlohmann_json//:json",
    ],
)
