load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "camera",
    srcs = ["camera.cc"],
    hdrs = ["camera.h"],
    deps = ["@glm"],
)

cc_library(
    name = "app_lib",
    srcs = [
        "app.cc",
        "live.cc",
        "music.cc",
        "stb_impl.cc",
    ],
    hdrs = ["app.h", "music.h"],
    linkopts = select({
        "@platforms//os:linux": ["-lasound", "-pthread"],
        "//conditions:default": [],
    }),
    deps = [
        ":camera",
        "//src/election",
        "//src/geo",
        "//src/news",
        "//src/render",
        "//src/store",
        "//src/ui",
        "@stb//:stb_image_write",
        "@system_glfw//:glfw",
    ],
)

cc_binary(
    name = "twn_election",
    srcs = ["main.cc"],
    data = [
        "//:assets",
        "//:data",
    ],
    deps = [":app_lib"],
)
