load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "results_tool",
    srcs = ["results_tool.cc"],
    deps = [
        "//src/election",
        "//src/geo",
    ],
)

cc_binary(
    name = "news_tool",
    srcs = ["news_tool.cc"],
    deps = [
        "//src/election",
        "//src/news",
        "//src/store",
        "@nlohmann_json//:json",
    ],
)
